GET {{host}}{{v1}}/stores/store/menus?store-id=63b4419c8571e6d2b86e8ef7&current-page=0&content-count=5&sort-name=order_count&direction=-1

###
POST {{host}}{{v1}}/stores/store/menus/menu
Content-Type: application/json

{
  "store_id":"63b4419c8571e6d2b86e8ef7",
  "name": "가게1의 메뉴1",
  "limit_count": "non",
  "possible": true,
  "price": 2000,
  "origin": "국내산",
  "description":"맛있어짱!"
}

###
POST {{host}}{{v1}}/stores/store/menus/menu
Content-Type: application/json

{
  "store_id":"63b4419c8571e6d2b86e8ef7",
  "name": "가게1의 메뉴2",
  "limit_count": "non",
  "possible": true,
  "price": 2000,
  "origin": "국내산",
  "description":"맛있어짱!"
}

###
POST {{host}}{{v1}}/stores/store/menus/menu
Content-Type: application/json

{
  "store_id":"63b13667c261c10ddffa2eb5",
  "name": "가게1의 메뉴3",
  "limit_count": "non",
  "possible": true,
  "price": 3000,
  "origin": "국내산",
  "description":"맛있어짱!"
}

###
PUT {{host}}{{v1}}/stores/store/menus/menu?menu-id=63b0f8f1e303f470c77b2d1c
Content-Type: application/json

{
  "store_id":"63b0f8bee303f470c77b2d1b",
  "name": "가게1의 메뉴1 수정이예용",
  "limit_count": "10",
  "possible": true,
  "price": 1000,
  "origin": "국내산",
  "description":"맛있어짱!"
}

###
DELETE {{host}}{{v1}}/stores/store/menus/menu?menu-id=63b0f8f1e303f470c77b2d1c

###
