POST {{host}}{{v1}}/orders/order
Content-Type: application/json

{
  "store_id": "63b82b009aea17d4a97e996d",
  "customer_id": "63b82a949aea17d4a97e996b",
  "menu_ids":["63b82b3f9aea17d4a97e996f"],
  "ordered_addr":{
    "street":"주문했어용",
    "detail":"오른쪽",
    "zip_code":"1241-21"
  },
  "phone_number": "010-3123-1111"
}
### => "order_id": "63b82e2b9aea17d4a97e9971", "order_numbering": "1673014827609181000-0"

###
PUT {{host}}{{v1}}/orders/order/customer
Content-Type: application/json

{
  "order_id": "63b82e2b9aea17d4a97e9971",
  "store_id": "63b82b009aea17d4a97e996d",
  "customer_id": "63b82a949aea17d4a97e996b",
  "menu_ids":[],
  "ordered_addr":{
    "street":"테스트거리수정집입니다.",
    "detail":"왼쪽으로바꾸겠습니다.",
    "zip_code":"1241-21"
  },
  "phone_number": "010-3234-4555"
}

###
PUT {{host}}{{v1}}/orders/order/store
Content-Type: application/json

{
  "order_id": "63b82e7d9aea17d4a97e9972",
  "store_id": "63b82b009aea17d4a97e996d",
  "user_id": "63b82a9a9aea17d4a97e996c",
  "status": "배달중"
}
###
###
GET {{host}}{{v1}}/orders/order/price?store-id=63b719a8df31b995028a1f97&menu-ids=63b71a449867c36ef6b7d514,63b71a7c9867c36ef6b7d515

###
GET {{host}}{{v1}}/orders/pages/customer?customer-id=63b6f63b697458e6fcdb4db3&status=배달중&current-page=0&content-count=5&sort-name=base_time.updated_at&direction=-1

###
GET {{host}}{{v1}}/orders/pages/store?store-id=63b6f65d697458e6fcdb4db5&status=배달중&current-page=0&content-count=5&sort-name=base_time.updated_at&direction=-1

