### -> 리뷰 작성
POST {{host}}{{v1}}/reviews/review
Content-Type: application/json

{
  "store_id": "63b82b009aea17d4a97e996d",
  "customer_id": "63b82a949aea17d4a97e996b",
  "menu_id": "63b82b3f9aea17d4a97e996f",
  "order_id": "63b82e2b9aea17d4a97e9971",
  "content": "진짜?정말?맛있어용!ㅎㅎㅎ",
  "rating": 3
}
###

### -> 메뉴별 리뷰보기
GET {{host}}{{v1}}/reviews/menu?menu-id=63b6f955b7b6269193c57f48&current-page=0&content-count=6&sort-name=base_time.updated_at&direction=-1

### -> 고객이 자신의 리뷰 보기
GET {{host}}{{v1}}/reviews/customer?customer-id=63b6f63b697458e6fcdb4db3&current-page=0&content-count=6&sort-name=base_time.updated_at&direction=-1

###