### -> 리뷰 작성
POST {{host}}{{v1}}/reviews/review
Content-Type: application/json

{
  "store_id": "63b6f65d697458e6fcdb4db5",
  "customer_id": "63b6f63b697458e6fcdb4db3",
  "menu_id": "63b6f955b7b6269193c57f48",
  "order_id": "63b70b8d6f4b7c5d037bf7cb",
  "content": "진짜?정말?맛있어용!ㅎㅎㅎ",
  "rating": 3
}
###

### -> 메뉴별 리뷰보기
GET {{host}}{{v1}}/reviews/menu?menu-id=63b6f955b7b6269193c57f48&current-page=0&content-count=6&sort-name=base_time.updated_at&direction=-1

### -> 고객이 자신의 리뷰 보기
GET {{host}}{{v1}}/reviews/customer?customer-id=63b6f63b697458e6fcdb4db3&current-page=0&content-count=6&sort-name=base_time.updated_at&direction=-1

###