POST {{host}}{{v1}}/stores/store
Content-Type: application/json

{
  "user_id": "63b7149b69e6b4a461ad9c56",
  "name": "가게2이예요.",
  "address": {
    "street": "테스트거리",
    "detail": "오른쪽입니다.",
    "zip_code": "1241-21"
  },
  "store_phone": "010-3333-2323"
}
### => 63b6f65d697458e6fcdb4db5

###
GET {{host}}{{v1}}/stores?current-page=0&content-count=6&sort-name=base_time.updated_at&direction=-1
### =>

###
# PUT의 recommend_menus 넣을경우 ==> 메뉴등록 선행필요
PUT {{host}}{{v1}}/stores/store?store-id=63b714aa69e6b4a461ad9c57
Content-Type: application/json

{
  "user_id": "63b7149b69e6b4a461ad9c56",
  "name": "가게1수정이예요1.",
  "address": {
    "street": "테스트거리",
    "detail": "오른쪽입니다.",
    "zip_code": "1241-21"
  },
  "store_phone": "010-6622-2323",
  "recommend_menus": []
}
###

###
GET {{host}}{{v1}}/stores/store/recommends?store-id=63b719a8df31b995028a1f97
Content-Type: application/json

###

