### -> user 생성 - customer => TODO 유저 타입 제한 필요
POST {{host}}{{v1}}/users/user
Content-Type: application/json

{
  "name": "테스트유저1",
  "nic_name":"테스트유저입니다용1",
  "password":"1234",
  "phone_number": "010-1111-3333",
  "role":"customer"
}
### => 63b82a949aea17d4a97e996b

### -> user 생성 - store => TODO 유저 타입 제한 필요
POST {{host}}{{v1}}/users/user
Content-Type: application/json

{
  "name": "테스트가게3",
  "nic_name":"테스트가게입니다용3",
  "password":"1234",
  "phone_number": "010-4444-1234",
  "role":"store"
}
### => 63b82a9a9aea17d4a97e996c
###
GET {{host}}{{v1}}/users/user?user-id=63b82a9a9aea17d4a97e996c

###
PUT {{host}}{{v1}}/users/user?user-id=63b82a9a9aea17d4a97e996c
Content-Type: application/json

{
  "name": "테스트2수정",
  "nic_name":"테스트입니다용2수정",
  "phone_number": "010-2233-7777",
  "role":"store"
}

###
DELETE {{host}}{{v1}}/users/user?user-id=63b6f577697458e6fcdb4dae