POST {{host}}{{v1}}/users/join
Content-Type: application/json

{
  "name": "테스트유저2",
  "nic_name":"테스트유저입니다용2",
  "password":"1234",
  "phone_number": "010-3333-4444",
  "role":"user"
}

###
POST {{host}}{{v1}}/users/join
Content-Type: application/json

{
  "name": "테스트가게2",
  "nic_name":"테스트가게입니다용2",
  "password":"1234",
  "phone_number": "010-5555-6666",
  "role":"store"
}