version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo-singlers
    restart: "no"
    ports:
      - 27017:27017
    volumes:
      - ~/mongo/data/singlers-db:/data/db
    command:
      - '--replSet'
      - 'singlers'
